/** Typed access to fixtures/golden/golden.json (generated by scripts/generate_golden.py). */
import { readFileSync } from "node:fs";

const url = new URL("../fixtures/golden/golden.json", import.meta.url);

export type Golden = {
  generatedFrom: { desktopVersion: string; desktopCommit: string };
  pure: {
    parseTimestamp: Array<{ input: string; seconds?: number; error?: string }>;
    formatTimestamp: Array<{ seconds: number; text: string }>;
    safeFilename: Array<{ input: string; output: string }>;
    resolveOutput: { existingFiles: string[]; requested: string; results: Record<string, string | null> };
    mediaKind: Record<string, "audio" | "video" | null>;
    audioExtensions: string[];
    imageExtensions: string[];
    videoExtensions: string[];
    audioOutputFormats: string[];
    videoOutputFormats: string[];
    versionTuple: Record<string, [number, number, number] | null>;
    isNewerVersion: Array<{ current: string; candidate: string; newer: boolean }>;
  };
  audio: unknown;
  effects: unknown;
};

export const golden = JSON.parse(readFileSync(url, "utf-8")) as Golden;
